spring.application.name=cakeshop

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cake_shop_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Jwt configuration
jwt.secret=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Google
google.client.id=209359598469-phrmbdmnhjncf87adusaf4eulcfo09af.apps.googleusercontent.com

# Cho phép ch?y data.sql sau khi Hibernate t?o b?ng xong
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always